### ISSUE TITLE
Potential DG bugs

### ISSUE THREAD

**Issue by XXJJXJ** [AY2122S1-CS2103T-T10-2/tp#224]
- [x] Also need to enlarge images, or if possible split into two diagrams cos people might complain it's too complicated
- [x] User stories and use cases: Should update to cover all the functionalities? also remove the `{More to be added}`
- [x] Add Event feature/Implementation Details: "Since Managera employs a UniqueEventList, it should not have more than one Event with the same name." This needs to be updated since Events can have the same name, just not same name and date. 
- [x] [Model] and [Storage] section need to update/improve
- [x] Model component: Only mentions `Participant` class, should mention `Event` class as well. 
- [x] DG review from CS2101 (@lowkangn )
Intro, Target Audience etc
- [x] AddParticipantByIndex is our AddParticipantToEvent, i.e. `enroll`. Needs updating (@kanjitp )
- [x] Filter Event feature/Design considerations: Diagram a bit small
- [x] [Proposed feature] section, can **remove** undo/redo command. Change to our "UndoneEventCommand" that we are going to implement, but not yet (Or remove all together, this is what other groups did) (enroll and expel multiple at once) (@XXJJXJ )
- [x] Update glossary
- [x] View Participants Details, i.e. `view` have been revamped to use Index. Needs updating 
- [x] View Event Details, i.e. `showDetails` have been revamped to use Index. Needs updating (@ntwbruce )
- [x] [Appendix: Instructions for manual testing] needs alot of work (@XXJJXJ )
- [x] NFR got this _`{more to be added}`_ , can remove
- [x] Update diagrams to remove Note and Tag from Participant
- [x] Remove [Completed] Header? (Looks a bit odd, compared to other group's DG)
- [x] Resize image to have text size similar to documentation text size

**Comment by ntwbruce** [comment]
- [ ] UI component: "depends on some classes in the `Model` component, as it displays ~`Person`~ `Event` or `Participant` object**s** residing..."
- [ ] Model component: Only mentions `Participant` class, should mention `Event` class as well. Also need to enlarge images, or if possible split into two diagrams cos people might complain it's too complicated
- [ ] Add Event feature/Implementation Details: "Since Managera employs a UniqueEventList, it should not have more than one Event with the same name." This needs to be updated since Events can have the same name, just not same name and date. 
- [ ] Filter Event feature/Implementation Details: "1. Date only, or 2. Date and Time"
- [ ] Filter Event feature/Implementation Rationale: "We feel that since all ~`Event`~ `Events` have a date..."
- [ ] Filter Event feature/Design considerations: Diagram a bit small
- [ ] User stories and use cases: Should update to cover all the functionalities? also remove the `{More to be added}`
